version: '3.7'
services:
        server:
                image: go-test
                environment:
                        HOST: 0.0.0.0
                        PORT: 8080
                configs:
                        - my-config
                secrets:
                        - my-secret
                ports:
                        - 8080:8080

configs:
        my-config:
                external: true

secrets:
        my-secret:
                external: true
